apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: davtroelkpyjs
  labels:
    app: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
    component: fastapi
    app.kubernetes.io/name: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
    app.kubernetes.io/instance: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
    app.kubernetes.io/component: fastapi
data:
  APP_NAME: "website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar"
  APP_ENV: "production"
  PYTHONUNBUFFERED: "1"
