apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-job-sa
  namespace: davtroelkpyjs
  labels:
    app: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
    component: kafka-topic-job
    app.kubernetes.io/name: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
    app.kubernetes.io/instance: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar
